name: 'Generates Release Notes'
description: 'Generates Markdown release notes from git history and Linear API.'
inputs:
  linear-api-key:
    description: 'Your Linear API Key.'
    required: true
  github-token:
    description: 'GitHub Token (usually secrets.GITHUB_TOKEN).'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Generator Script
      shell: bash
      env:
        # Map inputs to env vars for the script
        LINEAR_API_KEY: ${{ inputs.linear-api-key }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        
        # Pass GitHub Context to the script
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_REF_NAME: ${{ github.ref_name }}
        
      # ${{ github.action_path }} ensures it finds the script inside the action folder
      run: python3 ${{ github.action_path }}/generate_notes.py
